// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe1Hl9Tr4ZY48vUoPapLL1oocbEoVGDAc',
    appId: '1:630127149935:web:46673f8e6e78d385a6de9a',
    messagingSenderId: '630127149935',
    projectId: 'pendings-8bc24',
    authDomain: 'pendings-8bc24.firebaseapp.com',
    storageBucket: 'pendings-8bc24.firebasestorage.app',
    measurementId: 'G-Q9W0K0932R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCWVBSE05kMZwfQGWQ11XXGCBQA3c7b80',
    appId: '1:630127149935:android:ba3a6324e955cd97a6de9a',
    messagingSenderId: '630127149935',
    projectId: 'pendings-8bc24',
    storageBucket: 'pendings-8bc24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdOcN1hnBTZ7KzVZ-jE65rQhNxSRT6cdY',
    appId: '1:630127149935:ios:bbd22d445be94a6da6de9a',
    messagingSenderId: '630127149935',
    projectId: 'pendings-8bc24',
    storageBucket: 'pendings-8bc24.firebasestorage.app',
    iosClientId: '630127149935-be9v8srrhj8s30mnd43b3nlncre4g3lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pendings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdOcN1hnBTZ7KzVZ-jE65rQhNxSRT6cdY',
    appId: '1:630127149935:ios:bbd22d445be94a6da6de9a',
    messagingSenderId: '630127149935',
    projectId: 'pendings-8bc24',
    storageBucket: 'pendings-8bc24.firebasestorage.app',
    iosClientId: '630127149935-be9v8srrhj8s30mnd43b3nlncre4g3lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pendings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe1Hl9Tr4ZY48vUoPapLL1oocbEoVGDAc',
    appId: '1:630127149935:web:5946f0bb59e9b41ea6de9a',
    messagingSenderId: '630127149935',
    projectId: 'pendings-8bc24',
    authDomain: 'pendings-8bc24.firebaseapp.com',
    storageBucket: 'pendings-8bc24.firebasestorage.app',
    measurementId: 'G-EV5V8VD8HW',
  );

}